sudo: false
dist: trusty
language: java
jdk: openjdk11

# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

install:
  - export PRO_SPECIAL_BUILD="early-access-amber"
  - java pro_wrapper.java version

script:
  - ./pro/target/pro/bin/pro build build.pro
  
