sudo: false
dist: trusty
language: java
jdk: openjdk11

# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

install:
  - wget https://github.com/forax/valuetype-lambda/releases/download/untagged-c0d47fd5b9ddc8ecf1bb/jdk-12-concise-method.tar.gz
  - tar zxvf jdk-12-concise-method.tar.gz
  - export JAVA_HOME=jdk-12-concise-method
  - git clone https://github.com/forax/pro.git
  - cd pro
  - bash build.sh
  - cd ..

script:
  - ./pro/target/pro/bin/pro build build.pro
  
