sudo: false
dist: trusty
language: java

# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

install:
  - wget https://github.com/forax/java-next/releases/download/untagged-315f4fcd827ffdd40b11/jdk-13-concise-method-linux.tar.gz
  - tar zxvf jdk-13-concise-method-linux.tar.gz
  - export JAVA_HOME=`pwd`/jdk-13-concise-method
  - $JAVA_HOME/bin/java --version
  - git clone https://github.com/forax/pro.git
  - cd pro
  - bash build.sh
  - cd ..

script:
  - ./pro/target/pro/bin/pro build build.pro
  
